import Link from 'next/link'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

function fetchData() {
  return new Promise<string>((resolve) => {
    setTimeout(() => {
      resolve('RESULT')
    }, 1000); // 1 sec
  })
}


export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const result = await fetchData()
  return (
    <html lang="en">
       <body className={inter.className}>
        <header className='bg-red-500 flex items-center justify-center w-full h-60 flex-col'>
          <h1>TOP (LAYOUT: {result})</h1>
          <nav className="flex items-center gap-2">
            <Link href='/'>Home</Link>
            <Link href='/suspense'>Suspense</Link>
          </nav>
        </header>
        {children}
        <footer><h1 className="bg-blue-500 flex items-center justify-center w-full h-60">BOTTOM</h1></footer>
      </body>
    </html>
  )
}
