import Link from 'next/link'
import { Inter } from 'next/font/google'
import { InitApm } from './InitApm';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
       <body className={inter.className}>
        <InitApm></InitApm>
        <header className='bg-red-500 flex items-center justify-center w-full h-60 flex-col'>
          <h1>Header</h1>
          <nav className="flex items-center gap-2">
            <Link href='/'>Home</Link>
            <Link href='/page1'>Page1</Link>
            <Link href='/page2'>Page2</Link>
            <Link href='/page3'>Page3</Link>
          </nav>
        </header>
        {children}
        <footer><h1 className="bg-blue-500 flex items-center justify-center w-full h-60">Footer</h1></footer>
      </body>
    </html>
  )
}
